### ISSUE TITLE
Menampilkan notifikasi _toast_ atas aksi pengguna

### ISSUE THREAD

**Issue by sensasi-delight** [sensasi-apps/sensasi-pos#117]
Sebagai umpan balik sistem atas aksi pengguna, maka perlu ditampilkan pemberitahuan mengenai keberhasilan atas aksi tersebut dalam bentuk notifikasi toast.

### Discussed in https://github.com/sensasi-apps/sensasi-pos/discussions/116

<div type='discussions-op-text'>

<sup>Originally posted by **muchfahmiarif** September 18, 2024</sup>
Om @sensasi-delight saya ingin menambahkan fitur toast jika produk berhasil/gagal ditambahkan, tidak hanya fungsi toast bisa banyak. Penggunaan toast agar lebih interaktif dan mempermudah aksesibilitas</div>

**Comment by muchfahmiarif** [comment]
om @sensasi-delight toastnya baru 1, kan service nya pasti banyak. Jadi dianggap closed aja?

**Comment by sensasi-delight** [comment]
baik, berarti isu ini aku update menjadi lebih spesifik untuk mengurangi ambiguitas
