### ISSUE TITLE
Terjadi 'Overflow' pada Komponen Navbar pada Layar Kecil

### ISSUE THREAD

**Issue by theozebua** [sensasi-apps/sensasi-pos#139]
Ada _UI Overflow_ yang terjadi ketika sudah _"login"_.  Jadi karena _icon_-nya berderet, maka terjadilah _overflow_ pada _UI_-nya.

![image](https://github.com/user-attachments/assets/fc61ced8-8ba3-47de-aed0-a54e1d4953f9)

```ts
/**
 * Checks if the app has a logged in user
 */
export function hasLoggedInUser(): boolean {
  /**
   * @todo delete this when #85 is solved
   */
  return process.env.NODE_ENV !== 'production'

  // return !!localStorage.getItem('logged-in-user')
}
```

```ts
<NavbarContent justify="end">
  {hasLoggedInUser() ? <AuthNavbarItems /> : <GuestNavbarItems />}
</NavbarContent>
```

**Comment by sensasi-delight** [comment]
Isu valid dan terkonfirmsi.

**Comment by sensasi-delight** [comment]
Kemungkinan solusi:
Hanya tampilkan tombol 'hamburger'  pada perangkat dengan layar kecil yang jika diklik akan menampilkan navigasi ke halaman lain.

hal tersebut bisa dicapai dengan memodifikasi tombol pengaturan. mengubah ikonnya menjadi hamburger dan menampilkan navigasi ke halaman lain jika terdeteksi sedang diakses dengan perangkat berlayar kecil.

👍🏻: yay
👎🏻: nay
