### ISSUE TITLE
Membangun antarmuka halaman lupa kata sandi

### ISSUE THREAD

**Issue by sensasi-delight** [sensasi-apps/sensasi-pos#144]
kata sandi dan PIN dapat diatur ulang dengan cara:

- ~~Memasukkan kata sandi atau PIN jika pengguna belum terautentikasi~~
- Menjawab dua pertanyaan keamanan dengan benar. atau,
- Mengisi alamat surel dengan benar kemudian tautan dikirimkan melalui surel

**Comment by theozebua** [comment]
Mungkin diskusi dari isu #89 https://github.com/sensasi-apps/sensasi-pos/issues/89#issuecomment-2391163253 bisa kita lanjutkan di sini.

**Comment by theozebua** [comment]
Boleh di _assign_ ke aku aja bang 👌🏻

**Comment by sensasi-delight** [comment]
@theozebua GAAASSSS

**Comment by theozebua** [comment]
> kata sandi dan PIN dapat diatur ulang dengan cara:
> 
> * Memasukkan kata sandi atau PIN jika pengguna belum terautentikasi
> * Menjawab dua pertanyaan keamanan dengan benar. atau,
> * Mengisi alamat surel dengan benar kemudian tautan dikirimkan melalui surel

Cara pertama itu maksudnya gimana ya bang? Memasukkan kata sandi atau PIN jika pengguna belum terautentikasi.
Nah ini kan _forgot password_ bisa diakses ketika memang pengguna belum terotentikasi. Nah dia lupa kata sandi nih, terus dia harus masukin kata sandi atau PIN. Kan dia lupa kata sandi atau PIN-nya. Bagaimana dia mau mengatur ulang kata sandi kalau dia diminta untuk memasukkan kata sandi yang dia sendiri juga lupa? 🤔 

@sensasi-delight

**Comment by sensasi-delight** [comment]
Ide awalnya adalah bisa reset password dengan PIN atau reset PIN dengan password. namun sepertinya memang alur yang keliru ya karena pengguna secara alamiah akan mencoba masuk dengan PIN dan password secara bergantian jika salah satunya tidak berhasil.

sepertinya cara pertama tidak perlu diakomodir untuk reset password.

**Comment by theozebua** [comment]
Ohh begitu ya. Karena ku lihat juga di struktur data pengguna tidak ada PIN. hanya ada kata sandi.
Oke berarti kita hanya menggunakan 2 cara saja ya.

**Comment by sensasi-delight** [comment]
untuk struktur data model `user` saat ini memng belum final karena PIN akan disimpan pada properti `pin__hashed` dan belum tercantum pada file.

**Comment by theozebua** [comment]
Berarti untuk sementara, kita gunakan dua cara dulu kan? Cara 2 dan 3.
Karena PIN belum ada.
Nanti kalau memang PIN sudah ada, maka akan ditambahkan lagi cara yang pertama tadi sekaligus menambahkan metode _login_ dengan PIN, karena saat ini _login_ hanya bisa menggunakan kata sandi (UI).

**Comment by theozebua** [comment]
Nah untuk pertanyaannya keamanan ini bagaimana mekanismenya? Apakah pertanyaan keamanan setiap pengguna itu sama atau berbeda?

Kita harus mengetahui pengguna mana yang sedang lupa kata sandi dan ingin mengatur ulang kata sandinya. Nah cara tersebut bisa dengan memasukkan _identifier_ seperti surel (karena pengguna belum terotentikasi) atau dengan cara memilih pengguna seperti pada halaman _login_.

Bagaimana kira-kira?

**Comment by sensasi-delight** [comment]
bisa pilih akun dulu seperti yang dilakukan pada halaman login

**Comment by sensasi-delight** [comment]
Dear @theozebua,

PR #168 telah di-_merge_ namun isu belum ditutup karena diperlukan penyempurnaan pada formulir pertanyaan keamanan. 

Selain menjawab pertanyaan keamanan, pengguna juga harus memilih pertanyaan keamanan yang mereka pilih sebelumnya yang mana daftar pertanyaan tersebut baru saya tambahkan pada https://github.com/sensasi-apps/sensasi-pos/pull/169/commits/c7da9d73d64ce6352f7201d8f23f57102db82bde

Mohon akomodir penyempurnaan tersebut dengan PR yang baru.

Terima kasih banyak.

**Comment by theozebua** [comment]
Untuk antarmuka formulir pertanyaan keamanan sepertinya tidak ada yang berubah sih bang. Karena pada baris [ini](https://github.com/sensasi-apps/sensasi-pos/commit/3726d9acd7a166755d048d13169d7db3b27ca005#diff-43fd1f5fb9511225495d5574b1b31b223f6d7cd07ffecb47416f6bfbbef77dfbR39-R51) abang udah tambah `security_questions` di struktur datanya.

Jadi nanti tinggal melakukan perulangan saja pada _input field_-nya berdasarkan _security questions_ yang telah dia pilih.

![image](https://github.com/user-attachments/assets/e75108e5-d9d0-4eca-9704-cc9b32d31eb7)

Mungkin boleh ditambahkan _identifier_ pada setiap pertanyaan keamanan yang telah disimpan di _database_.

Bagaimana @sensasi-delight ? Apakah aku salah tangkap?

**Comment by theozebua** [comment]
**Menjawab dua pertanyaan keamanan dengan benar.**

Karena dari yang aku tangkap mekanismenya begini.
Ketika nanti pengguna sudah terdaftar, salah satu cara untuk mengamankan akun mereka adalah dengan memilih dua pertanyaan keamanan dari daftar yang ada pada https://github.com/sensasi-apps/sensasi-pos/commit/c7da9d73d64ce6352f7201d8f23f57102db82bde. Setelah mereka pilih, mereka berikan jawaban dari pertanyaan tersebut, lalu kedua pertanyaan keamanan tersebut beserta jawabannya disimpan ke dalam _database_.

Nah ketika mereka lupa kata sandi, maka mereka bisa memilih beberapa metode untuk memulihkan akun mereka. Salah satunya adalah menjawab dua pertanyaan keamanan yang telah mereka pilih sebelumnya. Nah pertanyaan keamanan tersebut nantinya akan berbeda disetiap akun. Nanti pertanyaan keamanan tersebut akan ditampilkan sesuai dengan pengguna yang telah dipilih.

Jadi menurutku tidak ada perubahan pada formulir pertanyaan keamanannya.

Bagaimana menurut abang? Mohon koreksi kalau aku salah tangkap bang @sensasi-delight 😄

**Comment by theozebua** [comment]
> dengan kata lain, dua pertanyaan yang dipilih pada registrasi jug perlu "ditebak" untuk mendapatkan tautan.

Itu maksudnya gimana bang?

Apakah maksudnya kita tampilkan daftar pertanyaan keamanan lalu mereka pilih dua diantaranya lalu mereka jawab?

**Comment by sensasi-delight** [comment]
benar sekali, aku pikir mekanisme tersebut lebih aman (dan paling optimal) dibanding dengan langsung menampilkan pertanyaan keamanan yang dipilih karena aplikasi ini bersifat luring yang mana pengguna-penggunanya pernah berinteraksi secara langsung.

Jika langsung menampilkan pertanyaan keamanan, maka terdapat kemungkinan untuk pegawai menebak-nebak jawaban pertanyaan keamanan milik manajer karena telah kenal dan berbicara secara langsung yang mungkin manajer tersebut pernah bercerita tentang warna favoritnya atau nama hewan peliharaan pertamanya.

**Comment by theozebua** [comment]
Aku juga mikir itu tadi sih, memang cara itu lebih aman daripada menampilkan pertanyaan yang telah dipilih dari _database_.

Oke, segera disempurnakan 🫡
