### ISSUE TITLE
redirect '/' ke '/coming-soon` selama masa pembangunan

### ISSUE THREAD

**Issue by sensasi-delight** [sensasi-apps/sensasi-pos#34]
Halaman '/' ditetapkan sebagai halaman antarmuka kasir/penjualan barang. halaman awal yang akan selalu dilihat pengguna.

**Comment by muchfahmiarif** [comment]
bang ko masi open? @sensasi-delight

**Comment by sensasi-delight** [comment]
ohh PR #39 tidak menggunakan [closing keywords](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests) yang sesuai makanya gak otomatis menutup
