### ISSUE TITLE
Membangun komponen `<Alert />`

### ISSUE THREAD

**Issue by sensasi-delight** [sensasi-apps/sensasi-pos#50]
Komponen dibangun menggunakan komponen `<Card />` milik NextUI namun memiliki fitur dasar seperti komponen `<Alert />` milik MUI

referensi:
- https://mui.com/material-ui/react-alert/
- https://nextui.org/docs/components/card

**Comment by muchfahmiarif** [comment]
assigned to me please

**Comment by sensasi-delight** [comment]
@muchfahmiarif waduh, ini lagi aku kerjain banh xixixi

**Comment by sensasi-delight** [comment]
komponen dibangun pada basis kode terpisah untuk kemaslahatan umat:
https://github.com/sensasi-delight/nextui-alert
