### ISSUE TITLE
bug saat menambahkan produk baru

### ISSUE THREAD

**Issue by muchfahmiarif** [sensasi-apps/sensasi-pos#82]
Terdapat bug setelah menambahkan produk baru :
`TypeError: Cannot read properties of undefined (reading 'reduce')`

**Comment by sensasi-delight** [comment]
penyebab:  #74
https://github.com/sensasi-delight/sensasi-pos/blob/15d98a80d2144240cdabed1abd4735a11882f0f2/src/models/table-types/product.ts#L26-L33
